[Hmk/url encryption] Fixed static file serving issues
globe-and-citizen/layer8-interceptor pull request #27
Opened 2024-07-29 10:50 UTC by huzaifamk

## PR Description
Fixed the issue of profile picture not appearing and static file was not being served properly.

## Manual Test Suite
SECTION 1: WEVE GOT POEMS (http://localhost:5173/)
[ ] Log in with 'tester' / '1234'
[ ] Log in anonymously with Layer8
[ ] Clicking "Get Next Poem" loads different poem correctly x 3
[ ] Clicking "Logout" takes you to the login screen
[ ] Clicking "Register" takes you to the registration page
[ ] Registering with a username, password, and profile image is successful
[ ] Logging in with the new username / password succeeds
[ ] Logging in with Layer8 opens the pop-up
[ ] Logging in with the "tester" & "12341234" works
[ ] User chooses to share their new "Username" & "Country" from the Layer8 Resource Server
[ ] Clicking "Get Next Poem" loads different poem correctly x 3
[ ] Clicking "Logout" takes you to the login page

SECTION 2: IMSHARER (http://localhost:5174/)
[ ] Main page loads
[ ] Upload of image works
[ ] Reload leads to instant reload (demonstrating proper caching)
[ ] Clicking the newly loaded image shows it in a light boxLog in using tester and 12341234 should succeed

2024-08-07 21:14 UTC, DeeStarks requested changes

2024-08-07 21:14 UTC, DeeStarks commented on .github/pull_request_template.md
Should we have this here? I thought it was only for use in the layer8 repo?

2024-08-07 21:14 UTC, DeeStarks commented on interceptor.go
> +
Do you mind explaining this process and what's expected? I would like to understand how the added `/media` works, what it changes, etc..

2024-08-07 21:14 UTC, DeeStarks commented on internals/main.go
> +  var url string
Could you run `go fmt ./...` to format the code?

```suggestion
    var url string
```

2024-08-14 09:35 UTC, huzaifamk commented on .github/pull_request_template.md
I will remove this.

2024-08-14 09:47 UTC, huzaifamk commented on interceptor.go
> +
`/media` is for static files, we define the same in the node backend, if you see this code:

`Go
app.use('/media', layer8_middleware.static('pictures'));
`

I am going to test and do some changes for making this dynamic, as I discussed this with Ravi, you will see a commit for it soon!

2024-08-14 21:15 UTC, DeeStarks reviewed
The code looks good to me, but I'm still not able to get the media to load. Perhaps I'm not doing something right?

![image](https://github.com/user-attachments/assets/aa89a740-d612-42c4-9f56-e8f05f3e9de4)

![image](https://github.com/user-attachments/assets/be361820-57fb-4a6b-a61e-fcbde0269f14)

![image](https://github.com/user-attachments/assets/ddded912-851a-4132-b748-7ef5d7b97489)

We can hop on a call sometime, maybe

2024-08-15 17:43 UTC, huzaifamk commented
> The code looks good to me, but I'm still not able to get the media to load. Perhaps I'm not doing something right?
> 
> ![image](https://private-user-images.githubusercontent.com/67328657/358008903-aa89a740-d612-42c4-9f56-e8f05f3e9de4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDM5OTgsIm5iZiI6MTcyMzc0MzY5OCwicGF0aCI6Ii82NzMyODY1Ny8zNTgwMDg5MDMtYWE4OWE3NDAtZDYxMi00MmM0LTlmNTYtZThmMDVmM2U5ZGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE3NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1Y2M1YzhhNDI2NWY5NDQxYTNmMDU0NWM1MzM5M2I5MjBjMTY5YTNkMWEzZmJhN2VmZDUyYWJiN2VmM2U5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7SXq5A0HOf9-huTrENqh5UORKoYPQ2DhPUzjxEmzFqE)
> 
> ![image](https://private-user-images.githubusercontent.com/67328657/358009210-be361820-57fb-4a6b-a61e-fcbde0269f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDM5OTgsIm5iZiI6MTcyMzc0MzY5OCwicGF0aCI6Ii82NzMyODY1Ny8zNTgwMDkyMTAtYmUzNjE4MjAtNTdmYi00YTZiLWE2MWUtZmNiZGUwMjY5ZjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE3NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmY2FlYjljYzgxZDVkMTFiYjk2ZGQ3ODZhM2FlNDEzNWVmNDc1ZWY2YmIyZmFhOGM0ZTE4NjE4NzE5YmQzOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1JEBlHnPaguJrkmbPyjTWS61zECS5Yy5SMljE60eP0E)
> 
> ![image](https://private-user-images.githubusercontent.com/67328657/358009474-ddded912-851a-4132-b748-7ef5d7b97489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NDM5OTgsIm5iZiI6MTcyMzc0MzY5OCwicGF0aCI6Ii82NzMyODY1Ny8zNTgwMDk0NzQtZGRkZWQ5MTItODUxYS00MTMyLWI3NDgtN2VmNWQ3Yjk3NDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE3NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTVlOGEyZjRmMzE5MmQ3YTI1NWE3NGI0N2Y3MjZhYzJmMDQ5MzYwYzU4MDQyOGEyODQ1OGFlNzg1Mzg0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q8gtirHjgPTKXb4u8O9-tAVMMmq-BgP58Xjffbha3f4)
> 
> We can hop on a call sometime, maybe

Let me test and fix this, let's see what's the issue here.

2024-08-18 19:14 UTC, huzaifamk commented
@DeeStarks I have pushed fixes for both middleware and interceptor, and also a new branch is here in layer8, which you can use with the new version of interceptor/middleware: https://github.com/globe-and-citizen/layer8/tree/hmk/url-encrypt-decrypt-feat

2024-08-21 08:36 UTC, DeeStarks approved these changes

2024-08-21 12:13 UTC, merged